# Makefile for generating track hub directory

HUBROOT=./hubroot
YAMLROOT=./yaml

.PHONY: hubroot

all: hubroot hub genomes tracks

hubroot:
	mkdir -p $(HUBROOT)
	mkdir -p $(HUBROOT)/hg19
	mkdir -p $(HUBROOT)/hg38

hub: hubroot $(HUBROOT)/hub.txt
genomes: hubroot $(HUBROOT)/genomes.txt
tracks: hubroot $(HUBROOT)/hg19/trackDb.txt $(HUBROOT)/hg38/trackDb.txt

# Writing explicit rules here since make < 3.81 can't figure out which to use

$(HUBROOT)/hub.txt:
	python python/render/render.py $(YAMLROOT)/hub/hub.yaml hub > $@

$(HUBROOT)/genomes.txt:
	python python/render/render.py $(YAMLROOT)/genomes/genomes.yaml genomes > $@

$(HUBROOT)/%/trackDb.txt:
	python python/render/render_tracks.py --proteins E2F1 --assembly $* --site_width 20bp > $@

clean:
	rm -rf $(HUBROOT)
